### ISSUE TITLE
Enhance "Help resources" section

### ISSUE THREAD

**Issue by michadu** [githubrsys/startingWithTYPO3#3]
Forger
You feel lost on forge.typo3.org? With all the tickets? Categories? Tracker? You do not know which patch you like to put your energy on review.typo3.org? You do not find those topics / reviews you have the best expertise?
So https://forger.typo3.org is probably the answer you are looking for!  It basically provides an intuitive interface to filter reviews and shows some statistics. In this article I will give you an overview over all the possible views.

Slack
The TYPO3 CMS team is using a tool called Slack kindly provided by https://slack.com/ to openly communicate with each other and with the public. "Slack" replaces the old "Skype meetings" in a more open, inviting and modern environment. The Slack tool is also used by plenty of other teams around the TYPO3 ecosphere so it is easier to interconnect teams.
If you want to join the Slack team, please register at http://forger.typo3.org/slack/.
Then join http://typo3.slack.com/ and our channel #typo3-cms.

**Comment by githubrsys** [comment]
Done. Thx for contrib. Next time a PR is welcome. http://githubrsys.github.io/startingWithTYPO3/#help-resources
